[2022-03-31 04:05:13,238] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: irctc_railway_train_schedules.flattening_data_spark_submit_task manual__2022-03-31T11:05:10.623530+00:00 [queued]>
[2022-03-31 04:05:13,248] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: irctc_railway_train_schedules.flattening_data_spark_submit_task manual__2022-03-31T11:05:10.623530+00:00 [queued]>
[2022-03-31 04:05:13,249] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-31 04:05:13,249] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-31 04:05:13,249] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-31 04:05:13,261] {taskinstance.py:1264} INFO - Executing <Task(SparkSubmitOperator): flattening_data_spark_submit_task> on 2022-03-31 11:05:10.623530+00:00
[2022-03-31 04:05:13,263] {standard_task_runner.py:52} INFO - Started process 4595 to run task
[2022-03-31 04:05:13,267] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'irctc_railway_train_schedules', 'flattening_data_spark_submit_task', 'manual__2022-03-31T11:05:10.623530+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/irctc_railway_train_schedules.py', '--cfg-path', '/tmp/tmpm7tzu7p6', '--error-file', '/tmp/tmpe_9q5p7_']
[2022-03-31 04:05:13,270] {standard_task_runner.py:77} INFO - Job 19: Subtask flattening_data_spark_submit_task
[2022-03-31 04:05:13,341] {logging_mixin.py:109} INFO - Running <TaskInstance: irctc_railway_train_schedules.flattening_data_spark_submit_task manual__2022-03-31T11:05:10.623530+00:00 [running]> on host ubuntu
[2022-03-31 04:05:13,391] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=irctc_railway_train_schedules
AIRFLOW_CTX_TASK_ID=flattening_data_spark_submit_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T11:05:10.623530+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-31T11:05:10.623530+00:00
[2022-03-31 04:05:13,397] {base.py:70} INFO - Using connection to: id: spark_submit_connection. Host: spark://ubuntu, Port: 7077, Schema: , Login: , Password: None, extra: {}
[2022-03-31 04:05:13,399] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://ubuntu:7077 --name arrow-spark --class com.hackprotech.railways.RailwaysDataFlatteningUsingDF /home/vengat/big_data/projects/spark_jars/spark-realtime-projects-assembly-2.0.0.jar
[2022-03-31 04:05:16,544] {spark_submit.py:488} INFO - 22/03/31 04:05:16 WARN Utils: Your hostname, ubuntu resolves to a loopback address: 127.0.1.1; using 192.168.232.128 instead (on interface ens33)
[2022-03-31 04:05:16,545] {spark_submit.py:488} INFO - 22/03/31 04:05:16 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2022-03-31 04:05:17,671] {spark_submit.py:488} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2022-03-31 04:05:17,671] {spark_submit.py:488} INFO - 22/03/31 04:05:17 WARN DependencyUtils: Local jar /home/vengat/big_data/projects/spark_jars/spark-realtime-projects-assembly-2.0.0.jar does not exist, skipping.
[2022-03-31 04:05:17,680] {spark_submit.py:488} INFO - Error: Failed to load class com.hackprotech.railways.RailwaysDataFlatteningUsingDF.
[2022-03-31 04:05:17,687] {spark_submit.py:488} INFO - 22/03/31 04:05:17 INFO ShutdownHookManager: Shutdown hook called
[2022-03-31 04:05:17,688] {spark_submit.py:488} INFO - 22/03/31 04:05:17 INFO ShutdownHookManager: Deleting directory /tmp/spark-81a73978-9ce8-4a91-ae2f-b3751d006a4b
[2022-03-31 04:05:17,759] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://ubuntu:7077 --name arrow-spark --class com.hackprotech.railways.RailwaysDataFlatteningUsingDF /home/vengat/big_data/projects/spark_jars/spark-realtime-projects-assembly-2.0.0.jar. Error code is: 101.
[2022-03-31 04:05:17,808] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=irctc_railway_train_schedules, task_id=flattening_data_spark_submit_task, execution_date=20220331T110510, start_date=20220331T110513, end_date=20220331T110517
[2022-03-31 04:05:17,828] {standard_task_runner.py:89} ERROR - Failed to execute job 19 for task flattening_data_spark_submit_task
Traceback (most recent call last):
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://ubuntu:7077 --name arrow-spark --class com.hackprotech.railways.RailwaysDataFlatteningUsingDF /home/vengat/big_data/projects/spark_jars/spark-realtime-projects-assembly-2.0.0.jar. Error code is: 101.
[2022-03-31 04:05:17,881] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-31 04:05:17,916] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
